name: MavenBuildAndDeploy

on:
  push:
    branches: [main]
    paths:
      - 'soa/**'
  pull_request:
    branches: [main]
    paths:
      - 'soa/**'

jobs:
  build-test-scan:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Java installation
        run: |
          echo "Java Version:"
          java -version
          echo "Maven Version:"
          mvn --version
          echo "Runner workspace root: $GITHUB_WORKSPACE"
          echo "Current directory: $(pwd)"
          echo "Workspace contents:"
          ls -R

      - name: Verify project structure
        run: |
          echo "Checking SOA projects exist:"
          ls -l soa/helloword/pom.xml
          ls -l soa/oracle-soa-project/pom.xml

      - name: Build helloword project
        working-directory: soa/helloword
        env:   
          MAVEN_OPTS: "-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
        run: mvn -B clean package

      - name: Build oracle-soa-project
        working-directory: soa/oracle-soa-project
        env:   
          MAVEN_OPTS: "-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
        run: mvn -B clean package

      - name: Setup WebLogic environment
        run: |
          echo "Setting up WebLogic environment variables"
          echo "WL_HOME: $WL_HOME"
          echo "ORACLE_HOME: $ORACLE_HOME"
          echo "PATH: $PATH"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Deploy helloword to WebLogic
        shell: powershell
        working-directory: soa/helloword
        env:
          WEBLOGIC_USERNAME: ${{ secrets.WEBLOGIC_USERNAME }}
          WEBLOGIC_PASSWORD: ${{ secrets.WEBLOGIC_PASSWORD }}
          WEBLOGIC_ADMIN_URL: ${{ secrets.WEBLOGIC_ADMIN_URL }}
          WEBLOGIC_TARGET_SERVER: ${{ secrets.WEBLOGIC_TARGET_SERVER }}
          JAR_PATH: target/sca_helloword_r